import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [location, setLocation] = useState('');
  const [data, setData] = useState({});
  const [weather, setWeather] = useState();
  const [errorMessage, setErrorMessage] = useState('');

  var apiKey = "b1801bbeb4d66c8609c9d891ced57586";
  var lang = "en";
  var units = "metric";
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${location}&units=${units}&appid=${apiKey}&lang=${lang}`//q represents the city name that we're gonna input into the input field


  const searchLocation = (event) => {
    if(event.key === "Enter") {
      axios.get(url)
      .then((response) => {
        //console.clear();
        setData(response.data)
        console.log(response.data);
        setWeather(response.data.weather);
        setErrorMessage("")
      }).catch(err => {
        console.log(err);
        setErrorMessage("Please enter a valid location");
        setData({});
        setWeather()
      })
      console.log(errorMessage);
      setLocation('')//clearing the input field
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {data.name}
        <input
          value={location}
          onChange={event => setLocation(event.target.value)}
          placeholder="Enter Location"
          onKeyDown={searchLocation}
          type="text"
        />

        {
          weather && weather.map((w, index) => {
            return(
              <div key={index}>
                <div>{w.description}</div>
                <div>Temperature: {data.main.temp} ℃</div>
                <div>Feels like:  {data.main.feels_like} ℃</div>
                {/* <div>Wind gust:   {data.wind.gust} m/s</div> */}
                {data.wind.gust && <div>Wind gust: {data.wind.gust} m/s</div>}
              </div>
            )
          })
        }
        {errorMessage && <div>{errorMessage}</div>}
        {/* can also write like this:
          {errorMessage ? <div>{errorMessage}</div> : null}
        */}
      </main>
    </>
  )
}
